algoritmo "Nome do Programa"

var
    x: real // 10.3
    y: inteiro //
    a: caractere
    l: logico


inicio 
    x <- 10.3
    y <- 10
    a <- "O Mick eh o homem mais lindo para a Priscila"
    l <- verdadeiro // falso

    escreval("X eh um real igual a " + x) 
    escreval("Y eh um inteiro igual a " + y)
    escreval("A eh um caractere igual a " + a)
    escreval("L eh um logico igual a " + l)



fimalgoritmo