Algoritmo "fatorial-funcao"

Var
n, f: inteiro

funcao fatorial(v: inteiro): inteiro
var
c, r: inteiro

Inicio
      r <- 1
      para c <- 1 ate v faca
           r <- r * c
      fimpara
      retorne R
fimfuncao

inicio
      escreva("Digite um numero: ")
      leia(n)
      f <- fatorial(n)
      escreval("O valor de ", n, "! eh igual a ", F)

Fimalgoritmo

//Este exerciocio mostra uma funcao funcionando.