Algoritmo "soma-funcao"

Var
v1, v2, s: inteiro

funcao soma(x, y: inteiro): inteiro
Inicio
      retorne x+ y
fimfuncao

inicio
      escreval("Digite o primeiro valor: ")
      leia(v1)
      escreval("Digite o segundo valor: ")
      leia(v2)
      s <- soma(v1, v2)
      
      escreval("A soma entre ", v1, " e ", v2, " e igual a ", s)


Fimalgoritmo

//Este exercicio serve para mostrar os diferentes os valores das variaveis em diferentes escopos mnnn