Algoritmo "semnome"

Var
nome: vetor[1..4] de caractere
n1: vetor[1..4] de real
n2: vetor[1..4] de real
m: vetor[1..4] de real
c: inteiro

Inicio
      para i <- 1 ate 4 faca
           escreval("Aluno ", i)
           escreva("Nome: ")
           leia(nome[i])
           escreva("Primeira nota: ")
           leia(n1[i])
           escreva("Segunda nota: ")
           leia(n2[i])
           m[i] <-
      fimpara

Fimalgoritmo